import { useCallback } from "react";
import { Download } from "lucide-react";
import { jsPDF } from "jspdf";
import { useUserProfile } from "@/app/context/UserProfileContext";
import type { UserProfile } from "@/app/types/userProfile";

function formatCoverDate(d: Date): string {
  const day = d.getDate();
  const month = d.toLocaleString("en-GB", { month: "long" });
  const year = d.getFullYear();
  return `${day} ${month} ${year}`;
}

function scoreRgb(score: number): [number, number, number] {
  if (score > 70) return [22, 163, 74];
  if (score >= 40) return [217, 119, 6];
  return [220, 38, 38];
}

function formatRisk(r: UserProfile["riskProfile"]): string {
  return r.charAt(0).toUpperCase() + r.slice(1);
}

function rupee(n: number): string {
  return `₹${n.toLocaleString("en-IN")}`;
}

function writeLines(
  doc: InstanceType<typeof jsPDF>,
  lines: string[],
  margin: number,
  startY: number,
  lineHeight: number,
  pageBottom: number,
): number {
  let y = startY;
  for (const line of lines) {
    if (y > pageBottom) {
      doc.addPage();
      y = margin;
    }
    doc.text(line, margin, y);
    y += lineHeight;
  }
  return y;
}

function buildPdf(profile: UserProfile): void {
  const doc = new jsPDF();
  const margin = 20;
  const pageW = doc.internal.pageSize.getWidth();
  const maxW = pageW - margin * 2;
  const pageBottom = doc.internal.pageSize.getHeight() - 15;
  const now = new Date();

  const score = profile.moneyHealthScore;
  const [sr, sg, sb] = scoreRgb(score);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(18);
  doc.setTextColor(0, 0, 0);
  doc.text("Money Mentor — Financial Health Report", margin, 35, { maxWidth: maxW });
  doc.setFontSize(11);
  doc.setTextColor(80, 80, 80);
  doc.text("Name", margin, 52);
  doc.setFontSize(13);
  doc.setTextColor(0, 0, 0);
  doc.text(profile.name?.trim() || "User", margin, 60);
  doc.setFontSize(12);
  doc.text(`Date: ${formatCoverDate(now)}`, margin, 70);

  doc.setFontSize(11);
  doc.setTextColor(60, 60, 60);
  doc.text("Money Health Score", margin, 98);
  doc.setFontSize(40);
  doc.setTextColor(sr, sg, sb);
  doc.text(String(score), margin, 124);
  doc.setFontSize(12);
  doc.setTextColor(sr, sg, sb);
  doc.text("out of 100", margin, 136);

  doc.addPage();
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(16);
  doc.text("This Month Summary", margin, 30);
  doc.setFontSize(11);
  let y = 48;
  doc.text(`Monthly Income: ${rupee(profile.monthlyIncome)}`, margin, y);
  y += 10;
  doc.text(`Monthly Expenses: ${rupee(profile.monthlyExpenses)}`, margin, y);
  y += 10;
  doc.text(`Monthly Savings: ${rupee(profile.monthlySavings)}`, margin, y);
  y += 10;
  doc.text(`Savings Rate: ${profile.savingsRate.toFixed(2)}%`, margin, y);

  doc.addPage();
  doc.setFontSize(16);
  doc.text("Financial Goals & Investments", margin, 30);
  doc.setFontSize(11);
  y = 45;
  doc.setTextColor(0, 0, 0);
  doc.text("Goals:", margin, y);
  y += 8;
  const goalsBody =
    profile.goals.length > 0
      ? profile.goals.map((g, i) => `${i + 1}. ${g}`).join("\n")
      : "No goals listed.";
  const goalLines = doc.splitTextToSize(goalsBody, maxW);
  y = writeLines(doc, goalLines, margin, y, 6, pageBottom);

  y += 8;
  if (y > pageBottom - 40) {
    doc.addPage();
    y = margin;
  }
  doc.text("Current investments:", margin, y);
  y += 8;
  const invBody =
    profile.currentInvestments.length > 0
      ? profile.currentInvestments.map((g, i) => `${i + 1}. ${g}`).join("\n")
      : "No investments listed.";
  const invLines = doc.splitTextToSize(invBody, maxW);
  y = writeLines(doc, invLines, margin, y, 6, pageBottom);

  y += 10;
  if (y > pageBottom - 20) {
    doc.addPage();
    y = margin;
  }
  doc.text(`Risk Profile: ${formatRisk(profile.riskProfile)}`, margin, y);
  y += 10;
  doc.text(`FIRE Age projection: ${profile.fireAge}`, margin, y);

  doc.addPage();
  doc.setFontSize(16);
  doc.text("Tax Savings Opportunity", margin, 30);
  doc.setFontSize(11);
  y = 48;
  doc.text(`Estimated annual tax savings: ${rupee(profile.estimatedTaxSavings)}`, margin, y);
  y += 10;
  doc.text(`Recommended monthly SIP: ${rupee(profile.recommendedSIP)}`, margin, y);
  y += 12;
  const noteLines = doc.splitTextToSize("Invest in ELSS funds to maximize 80C benefits", maxW);
  noteLines.forEach((line) => {
    doc.text(line, margin, y);
    y += 6;
  });

  doc.addPage();
  doc.setFontSize(14);
  doc.setTextColor(40, 40, 40);
  doc.text("Generated by Money Mentor — Your AI Financial Twin", margin, 60);
  doc.setFontSize(11);
  doc.text("Data is personalized based on your profile", margin, 78);
  doc.text(`Date and time of generation: ${now.toLocaleString("en-IN")}`, margin, 94);

  doc.save("money-mentor-report.pdf");
}

export function FinancialHealthReport() {
  const { profile } = useUserProfile();

  const onDownload = useCallback(() => {
    buildPdf(profile);
  }, [profile]);

  return (
    <button
      type="button"
      onClick={onDownload}
      className="inline-flex items-center gap-2 rounded-xl bg-gradient-to-r from-green-600 to-blue-600 px-4 py-2.5 text-sm font-medium text-white transition-all hover:opacity-95 hover:shadow-lg"
    >
      <Download className="h-4 w-4 shrink-0" aria-hidden />
      Download My Report
    </button>
  );
}
